"use client";
import {useState} from "react";
type Country="thailand"|"vietnam"; type Mode="packages"|"flights"|"hotels";
const data={thailand:{name:"Таиланд",flag:"🇹🇭",cities:["Пхукет","Паттайя","Бангкок","Самуи","Краби"]},vietnam:{name:"Вьетнам",flag:"🇻🇳",cities:["Нячанг","Фукуок","Дананг","Хошимин","Ханой"]}};
const deals=[["thailand","Пхукет","10 ночей",64000],["thailand","Паттайя","9 ночей",52000],["vietnam","Нячанг","10 ночей",57000],["vietnam","Фукуок","10 ночей",69000]] as const;
const money=(n:number)=>new Intl.NumberFormat("ru-RU").format(n)+" ₽";
export default function Home(){
 const [mode,setMode]=useState<Mode>("packages"),[country,setCountry]=useState<Country>("thailand"),[origin,setOrigin]=useState("Москва"),[city,setCity]=useState("Пхукет"),[date,setDate]=useState(""),[nights,setNights]=useState("10"),[guests,setGuests]=useState("2"),[budget,setBudget]=useState("100000"),[searched,setSearched]=useState(false);
 const d=data[country];
 const changeCountry=(c:Country)=>{setCountry(c);setCity(data[c].cities[0]);};
 const flight="https://www.google.com/travel/flights?q="+encodeURIComponent("Flights from "+origin+" to "+city+", "+d.name+(date?" on "+date:""));
 const hotel="https://www.booking.com/searchresults.html?ss="+encodeURIComponent(city+", "+d.name);
 const tour="https://www.google.com/search?q="+encodeURIComponent("тур "+d.name+" "+city+" из "+origin+" "+nights+" ночей");
 return <main>
 <header><div className="wrap nav"><div className="logo">✈ <b>Азия</b>Бюджет</div><nav><a href="#search">Поиск</a><a href="#deals">Варианты</a><a href="#how">Как работает</a></nav><a className="navBtn" href="#search">Найти поездку</a></div></header>
 <section className="hero"><div className="wrap heroGrid"><div><small className="eyebrow">БЮДЖЕТНЫЕ ПУТЕШЕСТВИЯ • 2026–2027</small><h1>Таиланд и Вьетнам<br/><em>по разумной цене</em></h1><p>Пакетные туры, отдельные перелёты и отели — с поиском по городу вылета, датам и бюджету.</p><div className="badges"><span>✓ Без комиссии за поиск</span><span>✓ Гибкие даты</span><span>✓ Сравнение вариантов</span></div></div><div className="heroCard"><small>ПОПУЛЯРНЫЕ НАПРАВЛЕНИЯ</small><div className="pop">🇹🇭 <div><b>Таиланд</b><span>Пхукет • Паттайя • Самуи</span></div><strong>от 52 000 ₽</strong></div><div className="pop">🇻🇳 <div><b>Вьетнам</b><span>Нячанг • Фукуок • Дананг</span></div><strong>от 57 000 ₽</strong></div><p className="note">Цены — ориентир для примера. Актуальная стоимость проверяется у поставщика.</p></div></div></section>
 <section className="search" id="search"><div className="wrap"><div className="searchBox"><div className="tabs"><button className={mode==="packages"?"active":""} onClick={()=>setMode("packages")}>🏝 Пакетные туры</button><button className={mode==="flights"?"active":""} onClick={()=>setMode("flights")}>✈ Авиабилеты</button><button className={mode==="hotels"?"active":""} onClick={()=>setMode("hotels")}>🏨 Отели</button></div><div className="countries"><button className={country==="thailand"?"active":""} onClick={()=>changeCountry("thailand")}>🇹🇭 Таиланд</button><button className={country==="vietnam"?"active":""} onClick={()=>changeCountry("vietnam")}>🇻🇳 Вьетнам</button></div><div className="fields"><label>Откуда<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label>Куда<select value={city} onChange={e=>setCity(e.target.value)}>{d.cities.map(c=><option key={c}>{c}</option>)}</select></label><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{mode!=="flights"&&<label>Ночей<select value={nights} onChange={e=>setNights(e.target.value)}><option>7</option><option>10</option><option>12</option><option>14</option><option>21</option></select></label>}{mode!=="hotels"&&<label>Гости<select value={guests} onChange={e=>setGuests(e.target.value)}><option>1</option><option>2</option><option>3</option><option>4</option></select></label>}<label>Бюджет<input value={budget} onChange={e=>setBudget(e.target.value)} inputMode="numeric"/></label><button className="find" onClick={()=>setSearched(true)}>Найти →</button></div>{searched&&<div className="result"><div><b>Поиск готов</b><span>{d.flag} {d.name} · {city} · {origin}{date?" · "+date:""}</span></div><a target="_blank" rel="noreferrer" href={mode==="flights"?flight:mode==="hotels"?hotel:tour}>Открыть предложения →</a></div>}</div></div></section>
 <section className="section" id="deals"><div className="wrap"><div className="head"><div><small className="eyebrow dark">ИДЕИ ДЛЯ ПОЕЗДКИ</small><h2>Бюджетные варианты</h2></div><p>Ориентиры для выбора направления. Кнопка откроет актуальный поиск.</p></div><div className="cards">{deals.filter(x=>x[0]===country).map((x,i)=><article className="card" key={x[1]}><div className={"visual v"+i}><span>{country==="thailand"?"🇹🇭":"🇻🇳"}</span><small>от {money(x[3])}</small></div><div className="body"><div className="row"><h3>{x[1]}</h3><span>{x[2]}</span></div><p>перелёт + отель · {guests} чел.</p><div className="bottom"><b>{money(x[3])}</b><button onClick={()=>{setCity(x[1]);setMode("packages");document.getElementById("search")?.scrollIntoView({behavior:"smooth"})}}>Подобрать →</button></div></div></article>)}</div></div></section>
 <section className="section light" id="how"><div className="wrap"><small className="eyebrow dark">ТРИ СПОСОБА</small><h2>Как найти дешевле</h2><div className="steps"><div><b>01</b><h3>Проверьте пакетный тур</h3><p>Иногда перелёт и отель вместе стоят дешевле отдельных покупок.</p></div><div><b>02</b><h3>Сравните авиабилеты</h3><p>Попробуйте соседние даты и разные аэропорты назначения.</p></div><div><b>03</b><h3>Проверьте отель отдельно</h3><p>Для длительной поездки самостоятельное бронирование может быть удобнее.</p></div></div></div></section>
 <section className="cta"><div className="wrap ctaIn"><div><small className="eyebrow">ГОТОВЫ К ПУТЕШЕСТВИЮ?</small><h2>Начните с вашего бюджета</h2></div><a href="#search">Подобрать поездку →</a></div></section>
 <footer><div className="wrap foot"><div className="logo">✈ <b>Азия</b>Бюджет</div><p>Сервис поиска и сравнения туристических вариантов. Цены и наличие уточняются на сайтах поставщиков.</p><small>© 2026</small></div></footer>
 </main>
}